### ISSUE TITLE
main.js deletion

### ISSUE THREAD

**Issue by etatus** [Wirecloud/map-viewer-hybrid-widget#4]
The file **js/main.js** is no longer used in current version and should be deleted.

**Comment by aarranz** [comment]
Hi etatus,

the `js/main.js` file is currently used, but in the w4t version of the widget (take a look into the [`w4t.html`](https://github.com/Wirecloud/map-viewer-hybrid-widget/blob/master/w4t.html) file).

I'm a bit busy these days and near vacations, but I will try to review all your pull requests.

Best regards,
Álvaro
